node {
  def remote = [:]
  remote.name = 'localhost.localdomain'
  remote.host = '192.168.254.157'
  remote.user = 'admendoza'
  remote.password = 'Stardelta03'
  remote.allowAnyHosts = true
  stage('Remote SSH') {
    sshCommand remote: remote, command: "ls -lrt"
    sshCommand remote: remote, command: "for i in {1..5}; do echo -n \"Loop \$i \"; date ; sleep 1; done"
  }
}